import React from 'react';

export default function InvoiceSummaryCard({ invoice }) {
  if (!invoice) return null;

  return (
    <div className="invoice-summary-card">
      <div className="summary-header">
        <h4>Invoice Summary</h4>
        <span className="invoice-number">{invoice.invoiceNumber}</span>
      </div>
      
      <div className="summary-details">
        <div className="detail-row">
          <span>Subtotal</span>
          <span>Rs. {invoice.subtotalAmount?.toFixed(2)}</span>
        </div>
        <div className="detail-row">
          <span>Discount</span>
          <span className="discount">- Rs. {invoice.discountAmount?.toFixed(2)}</span>
        </div>
        <div className="detail-row">
          <span>Tax</span>
          <span>Rs. {invoice.taxAmount?.toFixed(2)}</span>
        </div>
        <div className="detail-row total-row">
          <span>Total Amount</span>
          <span className="total-amount">Rs. {invoice.totalAmount?.toFixed(2)}</span>
        </div>
      </div>
      
      <div className="summary-meta">
        <div className="meta-item">
          <label>Payment Method</label>
          <p>{invoice.paymentMethod ? invoice.paymentMethod.replace(/_/g, ' ') : '—'}</p>
        </div>
        <div className="meta-item">
          <label>Payment Status</label>
          <p>
            <span className={`status-badge status-${invoice.paymentStatus?.toLowerCase()}`}>
              {invoice.paymentStatus}
            </span>
          </p>
        </div>
        <div className="meta-item">
          <label>Generated By</label>
          <p>{invoice.generatedByStaffName}</p>
        </div>
        <div className="meta-item">
          <label>Generated At</label>
          <p>{invoice.createdAt ? new Date(invoice.createdAt).toLocaleString() : '—'}</p>
        </div>
      </div>
      
      {invoice.notes && (
        <div className="summary-notes">
          <label>Notes</label>
          <p>{invoice.notes}</p>
        </div>
      )}
    </div>
  );
}
