spring.application.name=petcarehub
spring.profiles.active=dev

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/petcarehub
spring.datasource.username=root
spring.datasource.password=19112002@Aswg
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql= true

jwt.secret=yourSecretKeyForJWTTokenGenerationAndValidation2024

server.port=8080
#server.servlet.context-path=/api

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=prasannapradeepkumara90@gmail.com
spring.mail.password=ytfv bafc osjp qcvs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Frontend reset URL (change for prod)
#app.reset.url=http://localhost:5173/reset?token=

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet=DEBUG