import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { receiptService } from '../services/receiptService';
import InvoiceSummaryCard from '../components/InvoiceSummaryCard';
import InvoiceItemsTable from '../components/InvoiceItemsTable';
import '../styles/StaffReceipts.css';

export default function InvoiceDetailsPage() {
  const { invoiceId } = useParams();
  const navigate = useNavigate();
  const [invoice, setInvoice] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    fetchInvoice();
  }, [invoiceId]);

  const fetchInvoice = async () => {
    try {
      setLoading(true);
      const data = await receiptService.getInvoiceById(invoiceId);
      setInvoice(data);
      setError('');
    } catch (err) {
      console.error('Failed to fetch invoice:', err);
      setError('Failed to load invoice details. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return <div className="loading-state">Loading invoice details...</div>;
  }

  if (error) {
    return <div className="alert-error">{error}</div>;
  }

  if (!invoice) {
    return <div className="empty-state">Invoice not found.</div>;
  }

  return (
    <div className="invoice-details-page">
      <div className="invoice-details-header">
        <button className="btn-back" onClick={() => navigate('/dashboard/receipts')}>
          ← Back to Receipts
        </button>
        <h2>Invoice Details</h2>
      </div>

      <div className="invoice-details-content">
        <div className="invoice-info-section">
          <h3>Order Information</h3>
          <div className="info-grid">
            <div className="info-item">
              <label>Invoice Number</label>
              <p className="info-value">{invoice.invoiceNumber}</p>
            </div>
            <div className="info-item">
              <label>Order Number</label>
              <p className="info-value">{invoice.orderNumber}</p>
            </div>
            <div className="info-item">
              <label>Owner</label>
              <p className="info-value">{invoice.ownerName}</p>
            </div>
            <div className="info-item">
              <label>Email</label>
              <p className="info-value">{invoice.ownerEmail}</p>
            </div>
            <div className="info-item">
              <label>Pet</label>
              <p className="info-value">{invoice.petName} ({invoice.petSpecies})</p>
            </div>
            <div className="info-item">
              <label>Generated By</label>
              <p className="info-value">{invoice.generatedByStaffName}</p>
            </div>
          </div>
        </div>

        <div className="invoice-items-section">
          <h3>Invoice Items</h3>
          <InvoiceItemsTable items={invoice.items} />
        </div>

        <div className="invoice-summary-section">
          <InvoiceSummaryCard invoice={invoice} />
        </div>
      </div>
    </div>
  );
}
